### ISSUE TITLE
SPARQL 1.1 support

### ISSUE THREAD

**Issue by Flugtiger** [plt-tud/r43ples#32]
The currently used SPARQL syntax for querying the triplestore is not SPARQL 1.1 compliant. This becomes problematic as soon as one tries to use an other triplestore than virtuoso (tried with jena fuseki).

**Comment by markusgraube** [comment]
Yes, you are right that the code doesn't work with Jena fuseki since it has a different endpoint for querying and updating. However, I am not sure if this really breaks SPARQL 1.1 compatibilty (http://www.w3.org/TR/sparql11-protocol/).

At the end you are right, that this issue should be fixed.

**Comment by Flugtiger** [comment]
The different endpoints for query and update are no big problem. Currently each query is tested for update commands and based on this test an endpoint is selected.
A bigger problem is the changed syntax of update requests. In the SPARQL 1.0 update language (aka SPARUL) there was something like 
```
"INSERT INTO <graph> { ... }"
and
"DELETE FROM <graph> { ... }"
```
whereas SPARQL 1.1 only knows
```
"INSERT DATA { ... }"
"DELETE DATA { ... }"
and
"INSERT { ... }; DELETE { ... }; WHERE { ... }"
```
I tried to get some information on the exact update language currently used by virtuoso but I wasn't able to get anything at all.
BTW which virtuoso version do you use for testing? I had massive problems getting virtuoso to work at all. Currently I run a self-compiled 7.1 with a cherry-picked bugfix (wouldn't compile without).

**Comment by markusgraube** [comment]
Okay, now I see your point.

We should change it to the new syntax.

Currently I am using a self-compiled version (07.10.3207). Or you can just use the one used by the travis build (https://cloudstore.zih.tu-dresden.de/public.php?service=files&t=27bfa7d71ed6b9d3e3225da318cc4639&download). However, I don't know the exact version right now

**Comment by stephanhensel** [comment]
There is a bug in the current stable version of virtuoso which is only fixed in the develop branch.

A very quick way to get virtuoso to run is the following:
```
git clone https://github.com/openlink/virtuoso-opensource.git Virtuoso-Opensource
cd Virtuoso-Opensource
git checkout develop/7
apt-get install libtool gawk gperf autoconf automake libtool flex bison m4 make openssl libssl-dev
./autogen.sh
./configure
make
sudo checkinstall make install
```
