### ISSUE TITLE
Ontology weakness

### ISSUE THREAD

**Issue by Flugtiger** [plt-tud/r43ples#34]
I shortly stumbled across something which is in my opinion a weakness of the "RMO". The current version generates some information redundancy whenever two branches are merged. This is the result of having "commit" and "revision" separated when they basically refer to the same abstract object (each commit generates a single new revision and each revision is generated by only one single commit).

Whenever now two branches are merged, two separate commits are created both pointing to the same revision. This spawns problems when one wants to retrieve the (commit-)information of such a merging-revision since one can choose between two different sources of this information and there's no guaranty that they are consistent.

Even when no merging comes into play, one has always to do extra work to link the commits and revision together when creating a revision graph.

IMHO a better solution would be to merge the "commit" and "revision" classes together and allow multiple predecessors and successors.

**Comment by Flugtiger** [comment]
Seems I was mistaken and the redundant commits originated from the sparql query and not the dataset itself.

**Comment by markusgraube** [comment]
The basic idea to split revision and commit was allowing a commit to modify multiple graphs at once.
