### ISSUE TITLE
fast-forward merge

### ISSUE THREAD

**Issue by Flugtiger** [plt-tud/r43ples#35]
Fast forward merging is currently not supported. This means every merge generates a new revision even if one branch is a direct predecessor of the other branch. Together with issue #34 this creates some weird revision-graphs.

Graph before merging:
![revisiongraph_before_merge](https://cloud.githubusercontent.com/assets/3149624/5592373/3dae8022-91cc-11e4-8a4a-2edf473dd210.png)

Graph after merging:
![revisiongraph_after_merge](https://cloud.githubusercontent.com/assets/3149624/5592375/46731bf0-91cc-11e4-9499-ca18996a052b.png)

**Comment by stephanhensel** [comment]
Fast forward is now supported. Please have a look at b13cd3a0af7661525e0640e553e809e7680f77f0, there you will also find the corresponding revision graph structure. There is a special Fast Forward merge query (see documentation).
