### ISSUE TITLE
Bug bei zwei mal merging der gleichen Named Graph

### ISSUE THREAD

**Issue by YangXinyu** [plt-tud/r43ples#44]
ich habe eine Named Graph(z.b:<http://test.com/r43ples-dataset-merging> ) erzeugt, und die Mergequery eingeben, die Mergingprocess wird funktioniert , aber wenn ich die Mergequery bei der gleichen Named Graph eingeben, es wird zeigt: Named Graph is not exist.

Die Bug besteht in Endpoint->getMergeResponse()->MergeManagement.createRevisionProgress() Zeile: Endpoint : 951;

Da in MergeManagement.createRevisionProgress() die full graph gelöscht wird. 
Zeile:MergeManagement : 230

**Comment by markusgraube** [comment]
Right.
The question is whether the full graph is deleted at all. I will discuss with Stephan
