### ISSUE TITLE
Bug bei Select Query - Multiple Graphs

### ISSUE THREAD

**Issue by YangXinyu** [plt-tud/r43ples#45]
Anfrage:
"OPTION r43ples:SPARQL_JOIN
SELECT ?s ?p ?o 
FROM <http://test.com/r43ples-dataset-1> REVISION "master"
FROM <http://test.com/r43ples-dataset-2> REVISION "2"
WHERE {
  ?s ?p ?o. 
}"
wird nicht behandelt. Da die Endpoint kann OPTION nicht anerkennen.

**Comment by markusgraube** [comment]
Hi,
the current version of R43ples enables this option not with the keyword ``OPTION r43ples:SPARQL_JOIN`` but with an additional HTTP header parameter ``join_option``
