### ISSUE TITLE
New SPARQL revision interface via Query-Fragment

### ISSUE THREAD

**Issue by markusgraube** [plt-tud/r43ples#56]
Add new interface for specifying revisions via URL query fragment `revision` in Named Graph URI.

Besides
```
GRAPH <http://test.com/dataset> REVISION "2"
```
also following should be possible
```
GRAPH <http://test.com/dataset?revision=2>
```

**Comment by Tyr3al** [comment]
I have modified the two regular expressions that check and extract data from the SPARQL request. It should now be possible to use the two proposed versions. 

I have tested the results with these two queries:
`SELECT * 
WHERE { 
  GRAPH <http://test.com/r43ples-dataset-1> REVISION "2" {
    ?s ?p ?o 
  }
}`

`SELECT * 
WHERE { 
  GRAPH <http://test.com/r43ples-dataset-1?revision=2> {
    ?s ?p ?o 
  }
}`

The results were equal.

The modifications can be found in branch: [56_new_query_interface](https://github.com/plt-tud/r43ples/tree/56_new_query_interface)

**Comment by markusgraube** [comment]
I have opened PR #71  for your branch
