### ISSUE TITLE
Insert Query - Revision not referenced by a branch

### ISSUE THREAD

**Issue by splattater** [plt-tud/r43ples#79]
Hello,
I tried to use r43ples. You can find my setup here https://github.com/splattater/r43ples-docker.
I followed your instructions and struggle to insert data.

- `curl -L -d "query=CREATE GRAPH <http://example.org/>" http://localhost:8080/r43ples/sparql`
- `curl -L -d "query=USER \"mgraube\" MESSAGE \"test commit\" INSERT { GRAPH <http://example.org/> REVISION \"0\" { <Norman> <was> <here> .} }" http://localhost:8080/r43ples/sparql` ->  Revision is not referenced by a branch

How can I create a branch or is there something like a default branch?
Norman

**Comment by stephanhensel** [comment]
Hi Norman,
R43ples enumerate the revisions starting with "1". So you have to use "1" instead of "0". The default branch is "master" which you can use instead of the revision identifier. Further, within your query is the DATA keyword missing.
The following query should work for you:
`USER "mgraube" 
MESSAGE "test commit" 
INSERT DATA { GRAPH <http://example.org/> REVISION "1" { 
  <Norman> <was> <here> .
  }
}
`
Please give a short notice if it works.

Best regards,
Stephan

**Comment by splattater** [comment]
Hi Stephan,
thank you for your help. I tried out your example from above and got the following log entries:

- `23.08.2017 12:57:22 de.tud.plt.r43ples.webservice.Endpoint - SPARQL POST query (format: text/plain, query: CREATE GRAPH <http://example.org/>)`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.webservice.Endpoint - SPARQL request (format=text/plain, query_rewriting=false, header=) -> CREATE GRAPH <http://example.org/>`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.triplestoreInterface.TripleStoreInterfaceSingleton - Establishing connection to triplestore`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.triplestoreInterface.TripleStoreInterfaceSingleton - type: tdb`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.triplestoreInterface.TripleStoreInterfaceSingleton - url: database/dataset`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.triplestoreInterface.JenaTDBInterface - creating directory: database/dataset`
- `23.08.2017 12:57:22 de.tud.plt.r43ples.triplestoreInterface.JenaTDBInterface - Directory successfully created`
- `23.08.2017 12:57:23 de.tud.plt.r43ples.triplestoreInterface.TripleStoreInterface - Create sdd graph from data/data.ttl`
- `23.08.2017 12:57:39 de.tud.plt.r43ples.webservice.Endpoint - SPARQL POST query (format: text/plain, query: USER "mgraube" MESSAGE "test commit" INSERT DATA { GRAPH <http://example.org/> REVISION "1" { <Norman> <was> <here> .} })`
- `23.08.2017 12:57:39 de.tud.plt.r43ples.webservice.Endpoint - SPARQL request (format=text/plain, query_rewriting=false, header=) -> USER "mgraube" MESSAGE "test commit" INSERT DATA { GRAPH <http://example.org/> REVISION "1" { <Norman> <was> <here> .} }`
- `23.08.2017 12:57:39 de.tud.plt.r43ples.draftobjects.CommitDraft - No revision information available. Skip uptodate check!`
- `23.08.2017 12:57:39 de.tud.plt.r43ples.exception.InternalErrorException - Revision is not referenced by a branch`

**Comment by stephanhensel** [comment]
It seems that you are using the develop branch? Please switch to master, the develop branch is currently not very stable because we are restructuring a lot.

**Comment by splattater** [comment]
Hey Stephan,
I started r43ples using the master branch and got the following errors after CREATE-GRAPH-Query. https://gist.github.com/splattater/9861edc6155528832726b342bb1c2306

**Comment by stephanhensel** [comment]
There seems to be a problem with your configuration file. Normally it would use the sdd.ttl but in your case the file is called "data.ttl" as it does not exists you get the NullPointer. Did you change the configuration file? Can you please provide your configuration file that I can have look at it.

**Comment by splattater** [comment]
Ah, I got it. Changed my r43ples.conf file back to default settings. I thought it would be possible to name a turtle file (with content) that will be used when starting r43ples.
CREATE and INSERT DATA query are working now. Thank you.
